[EverforestDarkMedium]
;https://github.com/sainnhe/everforest
accent             = 83c092
accent-active      = 83c092
accent-inactive    = 2d353b
banner             = 83c092
border-active      = 83c092
border-inactive    = 343f44
header             = 475258
highlight          = 425047
main               = 2d353b
notification       = 83c092
notification-error = e67e80
subtext            = 859289
text               = D3c6aa
